### ISSUE TITLE
Generalize specification of actions

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#29]
Generalize the human-readable document (the markdown file) that specifies the actions we will support. Because there is high repetition of the conditions and effects associated with actions, we will generalize these factors to create a more adaptable version.

**Comment by lucyyutingli** [comment]
We had a meeting last night (5/9) and went through some of the things that we thought could be generalized. At this point, we’re not sure how general to go, but we came up with something like this:

Requirements:
Object must be accessible by player
Object must be able to be affected by action
Object must be in a state where action can be affective
Object’s requirements for action to be affective (if there are any) must be met

Effects:
Object’s state may be changed (used up, no longer accessible, no longer exists, etc.)
Object may not be able to be affected by current action after it is committed 
Object may no longer be able to be interacted with
Object’s position may be changed (from room, into inventory, dropped on the floor, etc.) 
Player state may be changed (super powers, new position, etc.)
Player’s inventory may be changed

**Comment by SnowballAntrobus** [comment]
Also changing the state of other objects as an effect? Or is that covered?

**Comment by lucyyutingli** [comment]
Good idea @SnowballAntrobus 
We can add something this to the effects:
Another object’s state is changed (now may be interact-able with, unlocked, etc.)

**Comment by lucyyutingli** [comment]
After today's meeting, we've decided to follow Borja's recommended template that will look like this:

4 action types
-------------
Generalizations for items/NPC
-------------
Any additional generalizations for actions.

**Comment by SnowballAntrobus** [comment]
*kinds :)

**Comment by lucyyutingli** [comment]
@borjasotomayor I remember you mentioning that should change where our README is located. Did you want us to put it directly in the docs folder and maybe rename it?

**Comment by borjasotomayor** [comment]
@lucyyutingli: Yes, you should move the file to `docs/actions.md`, and then update `docs/README.md` so it will include a link to the file (in the same way that the README links to the Developer Guidelines)

**Comment by lucyyutingli** [comment]
Thank you! Dante did it last night, it should be in the right place now.

**Comment by lucyyutingli** [comment]
@borjasotomayor So far we are following the template that you recommended yesterday, but now we're not sure if the way we're going about it is right. Currently, we have the "kinds" of actions on the top, then the requirements and effects for both items and npc's, and finally the list of actions with any unique requirements or effects that follow them. 

For example:
One of the requirements for items is that it is accessible by the player. However, when we work on the action "open" we don't know if a requirement that the item is unlocked should go under the unique requirements, since the item requirement for accessible by the player technically already covers that. At the moment, we are not sure if we should work on specifying requirements we already named in under the item category. 

You can find the file in the docs folder, at this link:  https://github.com/uchicago-cs/chiventure/blob/actions/dev/docs/actions.md

**Comment by borjasotomayor** [comment]
The document looks good, but it also seems too ambitious: are you planning on implementing every single possible condition and effect described in the document? You should also take into account that it will also be necessary to specify these conditions/effects in the WDL file.

There are also effects that seem like they create special cases that could be dealt with in a more general way. For example, look at the door and sconce objects in the distaff.wdl example file:

```
OBJECTS:
  - id: door
    short_desc: "A large wooden door"
    long_desc: "It looks very heavy, and it doesn't have a keyhole."
    locked: yes
    open: no
    actions:
      - open:
          - conditions:
             - locked: no
          - text_fail: "You can't open the door. It seems to be locked."
          - text_success: "You open the door."
      - walk:
          - conditions:
              - open: yes
          - text_fail: "You can't do that, the door is closed."

  - id: sconce
    short_desc: "A sconce holding a candle"
    long_desc: "It looks a bit loose."
    pulled: no
    actions:
      - take:
          - allowed: no
          - text_fail: "You can't do that. The sconce is loose, but still firmly attached to the wall."
      - pull:
          - conditions:
              - pulled: no
          - set:
              - object: door
                attribute: locked
                value: no
              - object: sconce
                attribute: pulled
                value: yes
          - text_success: "You pull on the sconce. You hear the sound of a door unlocking in a nearby room."
          - text_fail: "Pulling on the sconce again doesn't seem to do anything."
```

While this effectively translates to "the door can't be opened unless it is unlocked, and it is unlocked by pulling the sconce", the actions' conditions/effects are specified in a more general way. They really boil down to:

- The "open" action on `door` can only succeed if one of its attributes has a specific value.
- When you perform the "pull" action on `sconce`, it takes another object, and changes one of its attributes to another value

i.e.

- The "open" action on `door` can only succeed if one of its attributes **(the `locked` attribute)** has a specific value **(the value has to be `no`)**.
- When you perform the "pull" action on `sconce`, it takes another object **(the `door` object)**, and changes one of its attributes **(the `locked` attribute)** to another value **(the value `no`)**

I suspect that the vast majority of the conditions you've stated boil down to checking whether an attribute has some expected value, and most of the effects you've stated boil down to updating the attribute of an object. When that is the case, they shouldn't be treated as special cases.

Others, however, do require a special case. For example, if the effect of an action is that the object moves to another room, then that can't be specified simply as updating some attribute of that object)

**Comment by borjasotomayor** [comment]
Also, take into account that this document is intended as documentation for other teams. It can be helpful to put yourselves in their shoes, and see whether someone who's coming at this document out of the cold would understand what is going on (you can even ask someone from another team to give you some quick impressions). In particular, the "Kinds of Actions" section needs to be fleshed out: each kind of action should include a description and, ideally, a few examples.

Minor nit: you use `<ITEM>` early in the document and `[Item]` later on. You should use one form consistently (the former is probably best)

**Comment by lucyyutingli** [comment]
Thanks for all the help! I just want to make sure I'm understanding correctly. For a more general requirements, such as certain attributes being certain values, should we add something under <ITEM> at the top of list such as: 

- Item may need certain attribute to be a certain value before being accessible
- Item may change another item's attribute value


And then in the actions list change most of the actions to "no additional ..... needed," and find ones that only very specific actions can change, such as your change of position effect?

I'll also work on making the document more consistent! @borjasotomayor

**Comment by borjasotomayor** [comment]
Correct: Under "Items and NPC's" you would add these under "<ITEM>". You should also briefly explain what you mean by "requirements" and "effects" ("conditions" may be a better term than "requirements"). This can be as simple as explaining that, when an action is requested on an item/npc, it will only be carried out when certain conditions are met and, if they are, the action could have certain effects. So, what you're doing is describing the types of conditions and the type of effects that are allowed in all actions (and then you carve out the exceptions were appropriate) 

It may be helpful to start sketching how these conditions/effects would look in the WDL file and including that in the specification file. For example, the WDL code I posted above provides one possible mechanism for specifying conditions that check an attribute, and effects that alter an attribute. The WDL team would be responsible for figuring out the exact specification in the WDL format, and the actions document would, in the end, provide examples of how certain conditions/effects are specified in the WDL file.

Also, please note that "accessible" can be an ambiguous term (it sounds like you're referring to "can the action be performed on the item")

**Comment by lucyyutingli** [comment]
@borjasotomayor Do you think "reachable" might be a better term for accessible? We were trying to show that the item has to be in the same room as the player in order for the action to be able to be performed on. We could also take out that line entirely since we also have another condition that says "item must be able to be affected by action".

Also, we're not sure whether a new door being accessible is an "item" getting a new attribute value that allow the player to see that room, since almost all actions could lead to a new room being accesible.

**Comment by borjasotomayor** [comment]
You want to use language that is as unambiguous as possible. So, for example, you could simply say "the item must be in the same room as the player" (whether this has to be checked by you or by CLI is up for discussion, but you get to specify this as a requirement). Alternatively, you could include an explicit definition for "reachable", e.g.: "If an item is in the same room as the player, or is in the player's inventory, we refer to that item being *reachable*"

"item must be able to be affected by action" sounds like it refers to whether this action has been specified for this item in the WDL file. One thing you may want to do is to define what happens when the player tries to perform an action that is valid, but has not been specified for that item. You could have a further section of the document that specifies the default effects of actions (e.g., for pulling, it could simply be printing the message "I don't know how to pull on this")

Could you clarify what you mean by "a new door being accessible"?

**Comment by borjasotomayor** [comment]
Also, you may want to distinguish between conditions that will always be checked (e.g., "the item has to be in the same room as the player") and the ones that can be specified by the game designer in the WDL file (e.g., "an attribute of the item has to have a certain value"). You may want to specify the former separately from the "Conditions" and "Requirements" as simply being part of the definition of what is a valid <ITEM> for an action.

**Comment by lucyyutingli** [comment]
Sorry my wording wasn't clear, I meant a new room being accessible. For example, once opening a door, the player has a new room they can explore with new objects they can interact with. Is a new room being accessible considered an item gaining an attribute value that allows this to happen? I just wasn't sure if a new room being able to be explored would go under one of the conditions already listed or if it was a special case for some actions, or if this is assumed when a door is unlocked and the player walks through it.

**Comment by borjasotomayor** [comment]
I think this is going to require further discussion with Game State, so we should put it on the back burner for now. Rooms are not items, but we could potentially support something similar to what is in the distaff.wdl sample game: by default, you can move from one room to another freely, unless the game designer specified that one room is connected to another through an item (e.g., a door, a window, a trap door, etc.), and that item could have conditions that will prevent the "walk" action until the conditions are met.

**Comment by SnowballAntrobus** [comment]
Why would the conditions part of the WDL file be necessary?

`- conditions:
             - locked: no`

`- conditions:
              - pulled: no`

To me it feels like this is already encapsulated by the general way in which the actions are defined.

**Comment by SnowballAntrobus** [comment]
I created a new branch for the WDL and now also default behavior additions to actions.md.

Quick questions to discuss:
Are we doing to do weight? It probably does not make sense unless the PC has stats.
Are we going to handle multiple give_to for one NPC? How do we represent that in the WDL?
I think it might be easier to separate drink and eat based on how the WDL representation looks.

**Comment by borjasotomayor** [comment]
Because it provides a general-purpose way of specifying conditions: you can make an action depend on whether some attributes have a certain value, which is a much more powerful (and future-proof) mechanism than limiting actions to action-specific conditions (e.g., hardcoding that an item with the "open" action defined on it can only ever depend on whether the item is locked or not).

For example, suppose we have a door with two holes, such that the door will only open if a red gem and a green gem have been placed in the holes. The game could progress like this:

```
> OPEN door
You can't open the door. It seems to be locked.

> LOOK door
It looks like every door, except instead of a keyhole, it has two small holes on it. 
One is colored red, and the other green.

> USE red gem ON door
You place the red gem in one of the door's holes.

> USE green gem ON door.
You place the green gem in one of the door's holes.

> OPEN door
The door opens!
```

The WDL could look something like this:

```
  - id: door
    short_desc: "A wooden door"
    long_desc: "It looks like every door, except instead of a keyhole, it has two small holes on it. One is colored red, and the other green."
    has_red_gem: no
    has_green_gem: no
    open: no
    actions:
      - open:
          - conditions:
             - has_red_gem: yes
             - has_green_gem: yes
          - text_fail: "You can't open the door. It seems to be locked."
          - text_success: "You open the door."

  - id: red_gem
    short_desc: "A red gem"
    long_desc: "A red gem from Throxar the Terrible's treasure chest. You feel like having this gem will open new and exciting paths for you."
    actions:
      - use:
          - valid_recipients: door
          - set:
              - object: door
                attribute: has_red_gem
                value: yes
          - text_success: "You place the red gem in one of the door's holes."

# The green gem would be defined similarly
```

This would also make it easy to make conditions depend on attributes from *other* objects. For example, we could simplify the door item in distaff.wdl to have something like this:

```
    actions:
      - open:
          - conditions:
             - object: sconce
               attribute: pulled
               value: yes
          - text_fail: "You can't open the door. It seems to be locked."
          - text_success: "You open the door."
```
